### ISSUE TITLE
Can't install 0.5.5 from pypi

### ISSUE THREAD

**Issue by miha-plesko** [RedHatQE/taretto#15]
When I runfollowing command on Centos 7.5 with pip 18.1:

```
pip install taretto==0.5.5
```

I get following error:

```
Collecting taretto==0.5.5
Installing collected packages: taretto
Exception:
Traceback (most recent call last):
  File "/var/integration-tests/5.10.0.23/cfme_venv/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/var/integration-tests/5.10.0.23/cfme_venv/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/var/integration-tests/5.10.0.23/cfme_venv/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/var/integration-tests/5.10.0.23/cfme_venv/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/var/integration-tests/5.10.0.23/cfme_venv/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/var/integration-tests/5.10.0.23/cfme_venv/lib/python2.7/site-packages/pip/_internal/wheel.py", line 326, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: taretto==0.5.5 .dist-info directory not found
```

Any idea why?

**Comment by RonnyPfannschmidt** [comment]
at first glance this seems to be a misstake in packaging (the wheel should have been universal
at second glance its not clear why the build process itself fails you

please delete your pip cache and try again

**Comment by miha-plesko** [comment]
Thanks, I confirm 

```
pip install taretto==0.5.5 --no-cache-dir
```

solves the problem. Closing because build process may have failed due to missing system depencendies yesterday at first attempt :)
